### ISSUE TITLE
[Bug]: Opening an album from Starred results in an empty page: NumberFormatException.

### ISSUE THREAD

**Issue by DutchComputerKid** [kagemomiji/airsonic-advanced#233]
### What happened?

After migration this appeared. Exported starred songs to a playlist in Subsonic, imported into Airsonic and re-starred everything.
But clicking on the album when browing Starred results in an empty page. (See log)

### Steps to reproduce

1. Put a song in Starred
2. Open the album from the Starred page
3. Empty page appears, error is logged.

### Version

11.1.x (Edge)

### Version Detail

11.1.3-SNAPSHOT.20230527120152

### Operating System

Debian 11

### Java Version

openjdk 17.0.6 2023-01-17 (build 17.0.6+10-Debian-1deb11u1)

### Database

Other

### DB Detail

Built-In

### Configuration paramter

.

### Proxy Server

NGINX

### language

English

### Relevant log output

```console
2023-06-08 10:53:45.281 ERROR --- .WebSocketAnnotationMethodMessageHandler : Unhandled exception from message handler method
org.springframework.messaging.converter.MessageConversionException: Could not read JSON: Cannot deserialize Map key of type `java.lang.Integer` from String "Qntal/2018 - VIII - Nachtblume [Qobuz 16B-44.1kHz]": not a valid representation, problem: (java.lang.NumberFormatException) For input string: "Qntal/2018 - VIII - Nachtblume [Qobuz 16B-44.1kHz]"
at [Source: (byte[])"{"ids":[],"paths":{"Qntal/2018 - VIII - Nachtblume [Qobuz 16B-44.1kHz]":[""]}}"; line: 1, column: 20] (through reference chain: org.airsonic.player.ajax.MediaFileWSController$MediaDirectoryRequest["paths"]); nested exception is com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize Map key of type `java.lang.Integer` from String "Qntal/2018 - VIII - Nachtblume [Qobuz 16B-44.1kHz]": not a valid representation, problem: (java.lang.NumberFormatException) For input string: "Qntal/2018 - VIII - Nachtblume [Qobuz 16B-44.1kHz]"
at [Source: (byte[])"{"ids":[],"paths":{"Qntal/2018 - VIII - Nachtblume [Qobuz 16B-44.1kHz]":[""]}}"; line: 1, column: 20] (through reference chain: org.airsonic.player.ajax.MediaFileWSController$MediaDirectoryRequest["paths"])
at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:237) ~[spring-messaging-5.3.27.jar!/:5.3.27]
at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:185) ~[spring-messaging-5.3.27.jar!/:5.3.27]
at org.springframework.messaging.converter.CompositeMessageConverter.fromMessage(CompositeMessageConverter.java:70) ~[spring-messaging-5.3.27.jar!/:5.3.27]
at org.springframework.messaging.handler.annotation.support.PayloadMethodArgumentResolver.resolveArgument(PayloadMethodArgumentResolver.java:138) ~[spring-messaging-5.3.27.jar!/:5.3.27]
at org.springframework.messaging.handler.invocation.HandlerMethodArgumentResolverComposite.resolveArgument(HandlerMethodArgumentResolverComposite.java:118) ~[spring-messaging-5.3.27.jar!/:5.3.27]
at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.getMethodArgumentValues(InvocableHandlerMethod.java:147) ~[spring-messaging-5.3.27.jar!/:5.3.27]
at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:115) ~[spring-messaging-5.3.27.jar!/:5.3.27]
at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMatch(AbstractMethodMessageHandler.java:569) ~[spring-messaging-5.3.27.jar!/:5.3.27]
at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:511) ~[spring-messaging-5.3.27.jar!/:5.3.27]
at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:94) ~[spring-messaging-5.3.27.jar!/:5.3.27]
at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessageInternal(AbstractMethodMessageHandler.java:524) ~[spring-messaging-5.3.27.jar!/:5.3.27]
at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessage(AbstractMethodMessageHandler.java:458) ~[spring-messaging-5.3.27.jar!/:5.3.27]
at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:144) ~[spring-messaging-5.3.27.jar!/:5.3.27]
at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136) ~[na:na]
at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635) ~[na:na]
at java.base/java.lang.Thread.run(Thread.java:833) ~[na:na]
Caused by: com.fasterxml.jackson.databind.exc.InvalidFormatException: Cannot deserialize Map key of type `java.lang.Integer` from String "Qntal/2018 - VIII - Nachtblume [Qobuz 16B-44.1kHz]": not a valid representation, problem: (java.lang.NumberFormatException) For input string: "Qntal/2018 - VIII - Nachtblume [Qobuz 16B-44.1kHz]"
at [Source: (byte[])"{"ids":[],"paths":{"Qntal/2018 - VIII - Nachtblume [Qobuz 16B-44.1kHz]":[""]}}"; line: 1, column: 20] (through reference chain: org.airsonic.player.ajax.MediaFileWSController$MediaDirectoryRequest["paths"])
at com.fasterxml.jackson.databind.exc.InvalidFormatException.from(InvalidFormatException.java:67) ~[jackson-databind-2.13.5.jar!/:2.13.5]
at com.fasterxml.jackson.databind.DeserializationContext.weirdKeyException(DeserializationContext.java:1968) ~[jackson-databind-2.13.5.jar!/:2.13.5]
at com.fasterxml.jackson.databind.DeserializationContext.handleWeirdKey(DeserializationContext.java:1173) ~[jackson-databind-2.13.5.jar!/:2.13.5]
at com.fasterxml.jackson.databind.deser.std.StdKeyDeserializer.deserializeKey(StdKeyDeserializer.java:138) ~[jackson-databind-2.13.5.jar!/:2.13.5]
at com.fasterxml.jackson.databind.deser.std.MapDeserializer._readAndBind(MapDeserializer.java:531) ~[jackson-databind-2.13.5.jar!/:2.13.5]
at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:440) ~[jackson-databind-2.13.5.jar!/:2.13.5]
at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:32) ~[jackson-databind-2.13.5.jar!/:2.13.5]
at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:129) ~[jackson-databind-2.13.5.jar!/:2.13.5]
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserializeFromObject(BeanDeserializer.java:392) ~[jackson-databind-2.13.5.jar!/:2.13.5]
at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:185) ~[jackson-databind-2.13.5.jar!/:2.13.5]
at com.fasterxml.jackson.databind.deser.DefaultDeserializationContext.readRootValue(DefaultDeserializationContext.java:323) ~[jackson-databind-2.13.5.jar!/:2.13.5]
at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:4674) ~[jackson-databind-2.13.5.jar!/:2.13.5]
at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:3723) ~[jackson-databind-2.13.5.jar!/:2.13.5]
at org.springframework.messaging.converter.MappingJackson2MessageConverter.convertFromInternal(MappingJackson2MessageConverter.java:223) ~[spring-messaging-5.3.27.jar!/:5.3.27]
... 15 common frames omitted
```

**Comment by kagemomiji** [comment]
This is fixed by https://github.com/kagemomiji/airsonic-advanced/commit/10f7d851e05b7ab08af9501ca1738b5f196e0dfb
