### ISSUE TITLE
[Bug]: album art not show up on third party apps

### ISSUE THREAD

**Issue by yuygfgg** [kagemomiji/airsonic-advanced#440]
### What happened?

The album are do not show up, but songs covers show correctly. 
![song list show correctly](https://img2.imgtp.com/2024/05/01/wLqXhuSY.PNG)
![album list no art](https://img2.imgtp.com/2024/05/01/kBoJdU2z.PNG)
![single song with cover](https://img2.imgtp.com/2024/05/01/iNUvwUli.PNG)
![single album no cover](https://img2.imgtp.com/2024/05/01/BrcEFkFX.PNG)

### Steps to reproduce

just add the server, using subsonic api

### Version

11.1.3 (Stable)

### Operating System

ubuntu 22.04 TLS

### Java Version

openjdk 19.0.2 2023-01-17

### Database

MariaDB 8.x, Other

### DB Detail

I don't know. I'm didn't change db myself.

### Configuration paramter

```
# Airsonic preferences.  NOTE: This file is automatically generated. Do not modify while application is running

JWTKey=
SettingsChanged=
EncryptionKeyPassword=
EncryptionKeySalt=
IndexCreationInterval=1
IndexCreationHour=3
FastCacheEnabled=true
OrganizeByFolderStructure=true
UploadsFolder=%{['USER_MUSIC_FOLDERS'][0]}/Incoming
ExcludePattern=
IgnoreSymLinks=false
EnableCueIndexing=true
HideIndexedFiles=true
FullScan=false
ClearFullScanSettingAfterScan=false
IndexString=A B C D E F G H I J K L M N O P Q R S T U V W X-Z(XYZ)
IgnoredArticles=The El La Los Las Le Les
GenreSeparators=;
Shortcuts=New Incoming Podcast
PlaylistFolder=/var/playlists
MusicFileTypes=mp3 ogg oga aac m4a m4b flac wav wma aif aiff ape mpc shn mka opus alm 669 mdl far xm mod fnk imf it liq wow mtm ptm rtm stm s3m ult dmf dbm med okt emod sfx m15 mtn amf gdm stx gmc psm j2b umx amd rad hsc flx gtk mgt mtp wv
VideoFileTypes=flv avi mpg mpeg mp4 m4v mkv mov wmv ogv divx m2ts webm
CoverArtFileTypes2=cover.jpg cover.png cover.gif folder.jpg jpg jpeg gif png
CoverArtSource=FILETAG
CoverArtConcurrency=4
CoverArtQuality=90
SortAlbumsByYear=true
GettingStartedEnabled=false
WelcomeTitle=Welcome to Airsonic!
WelcomeSubtitle=
WelcomeMessage2=__Welcome to Airsonic!__\r\n\\\\ \\\\\r\nAirsonic is a free, web-based media streamer, providing ubiquitous access to your music. \r\n\\\\ \\\\\r\nUse it to share your music with friends, or to listen to your own music while at work. You can stream to multiple players simultaneously, for instance to one player in your kitchen and another in your living room.\r\n\\\\ \\\\\r\nTo change or remove this message, log in with administrator rights and go to <a href='settings.view'>Settings</a> > <a href='generalSettings.view'>General</a>.
LoginMessage=
server.servlet.session.timeout=30m
Theme=default
LocaleLanguage=zh
LocaleCountry=CN
LocaleVariant=
SplitOptions=-ss %o -t %d
SplitCommand=ffmpeg %S -i %s -vcodec copy -acodec copy -f %f -
DownsamplingCommand4=ffmpeg %S -i %s -map 0:0 -b:a %bk -v 0 -f mp3 -
HlsCommand4=ffmpeg -ss %o -i %s -s %wx%h -async 1 -c:v libx264 -flags +cgop -b:v %vk -maxrate %bk -preset superfast -copyts -b:a %rk -bufsize 256k -map 0:0 -map 0:%i -ac 2 -ar 44100 -v 0 -threads 0 -force_key_frames expr:gte(t,n_forced*10) -start_number %j -hls_time %d -hls_list_size 0 -hls_segment_filename %n %p
JukeboxCommand2=ffmpeg -ss %o -i %s -map 0:0 -v 0 -ar 44100 -ac 2 -f s16be -
VideoImageCommand=ffmpeg -r 1 -ss %o -t 1 -i %s -s %wx%h -v 0 -f mjpeg -
SubtitlesExtractionCommand=ffmpeg -i %s -map 0:%i -f %f -
TranscodeEstimateTimePadding=2000
TranscodeEstimateBytePadding=0
DlnaEnabled=true
DlnaServerName=Airsonic
# Airsonic preferences.  NOTE: This file is automatically generated. Do not modify while application is running
```

### language

None

### Relevant log output

```console
no relevant logs I think.
```

**Comment by yuygfgg** [comment]
Some error log occur when scanning library
```
2024-05-01 21:34:04.495  INFO --- o.a.p.s.MediaScannerService              : Persisting albums
2024-05-01 21:34:04.545  INFO --- o.a.p.s.MediaScannerService              : Persisting artists
2024-05-01 21:34:04.557  INFO --- o.a.p.s.MediaScannerService              : Persisting genres
2024-05-01 21:34:08.633  WARN --- o.h.e.j.spi.SqlExceptionHelper           : SQL Error: -104, SQLState: 23505
2024-05-01 21:34:08.633 ERROR --- o.h.e.j.spi.SqlExceptionHelper           : integrity constraint violation: unique constraint or index violation: IDX_ARTIST_NAME
2024-05-01 21:34:08.942  INFO --- o.a.p.s.MediaScannerService              : Marking non-present albums.
2024-05-01 21:34:08.942  INFO --- o.a.p.s.MediaScannerService              : Updating genres
2024-05-01 21:34:08.974  INFO --- o.a.p.s.MediaScannerService              : Album persistence complete
2024-05-01 21:34:09.010  INFO --- o.a.p.s.MediaScannerService              : Genre persistence successfully complete: true
2024-05-01 21:34:09.014 ERROR --- o.a.p.s.MediaScannerService              : Failed to scan media library.

java.util.concurrent.CompletionException: org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
        at java.base/java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:315) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:320) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1770) ~[na:na]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1760) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:387) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1311) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1841) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1806) ~[na:na]
        at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177) ~[na:na]
Caused by: org.springframework.dao.DataIntegrityViolationException: could not execute statement; SQL [n/a]; constraint [null]; nested exception is org.hibernate.exception.ConstraintViolationException: could not execute statement
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.convertHibernateAccessException(HibernateJpaDialect.java:276) ~[spring-orm-5.3.31.jar!/:5.3.31]
        at org.springframework.orm.jpa.vendor.HibernateJpaDialect.translateExceptionIfPossible(HibernateJpaDialect.java:233) ~[spring-orm-5.3.31.jar!/:5.3.31]
        at org.springframework.orm.jpa.AbstractEntityManagerFactoryBean.translateExceptionIfPossible(AbstractEntityManagerFactoryBean.java:551) ~[spring-orm-5.3.31.jar!/:5.3.31]
        at org.springframework.dao.support.ChainedPersistenceExceptionTranslator.translateExceptionIfPossible(ChainedPersistenceExceptionTranslator.java:61) ~[spring-tx-5.3.31.jar!/:5.3.31]
        at org.springframework.dao.support.DataAccessUtils.translateIfNecessary(DataAccessUtils.java:243) ~[spring-tx-5.3.31.jar!/:5.3.31]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:152) ~[spring-tx-5.3.31.jar!/:5.3.31]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.31.jar!/:5.3.31]
        at org.springframework.data.jpa.repository.support.CrudMethodMetadataPostProcessor$CrudMethodMetadataPopulatingMethodInterceptor.invoke(CrudMethodMetadataPostProcessor.java:174) ~[spring-data-jpa-2.7.18.jar!/:2.7.18]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.31.jar!/:5.3.31]
        at org.springframework.aop.interceptor.ExposeInvocationInterceptor.invoke(ExposeInvocationInterceptor.java:97) ~[spring-aop-5.3.31.jar!/:5.3.31]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.31.jar!/:5.3.31]
        at org.springframework.aop.framework.JdkDynamicAopProxy.invoke(JdkDynamicAopProxy.java:241) ~[spring-aop-5.3.31.jar!/:5.3.31]
        at jdk.proxy2/jdk.proxy2.$Proxy225.save(Unknown Source) ~[na:na]
        at org.airsonic.player.service.ArtistService.save_aroundBody10(ArtistService.java:203) ~[classes!/:11.1.3]
        at org.airsonic.player.service.ArtistService$AjcClosure11.run(ArtistService.java:1) ~[classes!/:11.1.3]
        at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96cproceed(AbstractTransactionAspect.aj:67) ~[spring-aspects-5.3.31.jar!/:5.3.31]
        at org.springframework.transaction.aspectj.AbstractTransactionAspect$AbstractTransactionAspect$1.proceedWithInvocation(AbstractTransactionAspect.aj:73) ~[spring-aspects-5.3.31.jar!/:5.3.31]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.31.jar!/:5.3.31]
        at org.springframework.transaction.aspectj.AbstractTransactionAspect.ajc$around$org_springframework_transaction_aspectj_AbstractTransactionAspect$1$2a73e96c(AbstractTransactionAspect.aj:71) ~[spring-aspects-5.3.31.jar!/:5.3.31]
        at org.airsonic.player.service.ArtistService.save(ArtistService.java:202) ~[classes!/:11.1.3]
        at org.airsonic.player.service.MediaScannerService.lambda$17(MediaScannerService.java:296) ~[classes!/:11.1.3]
        at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1768) ~[na:na]
        ... 6 common frames omitted
Caused by: org.hibernate.exception.ConstraintViolationException: could not execute statement
        at org.hibernate.exception.internal.SQLExceptionTypeDelegate.convert(SQLExceptionTypeDelegate.java:59) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.exception.internal.StandardSQLExceptionConverter.convert(StandardSQLExceptionConverter.java:37) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:113) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.engine.jdbc.spi.SqlExceptionHelper.convert(SqlExceptionHelper.java:99) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:200) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.dialect.identity.GetGeneratedKeysDelegate.executeAndExtract(GetGeneratedKeysDelegate.java:58) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.id.insert.AbstractReturningDelegate.performInsert(AbstractReturningDelegate.java:43) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3279) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.persister.entity.AbstractEntityPersister.insert(AbstractEntityPersister.java:3914) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.action.internal.EntityIdentityInsertAction.execute(EntityIdentityInsertAction.java:84) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.engine.spi.ActionQueue.execute(ActionQueue.java:645) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.engine.spi.ActionQueue.addResolvedEntityInsertAction(ActionQueue.java:282) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.engine.spi.ActionQueue.addInsertAction(ActionQueue.java:263) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.engine.spi.ActionQueue.addAction(ActionQueue.java:317) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.event.internal.AbstractSaveEventListener.addInsertAction(AbstractSaveEventListener.java:329) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.event.internal.AbstractSaveEventListener.performSaveOrReplicate(AbstractSaveEventListener.java:286) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.event.internal.AbstractSaveEventListener.performSave(AbstractSaveEventListener.java:192) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.event.internal.AbstractSaveEventListener.saveWithGeneratedId(AbstractSaveEventListener.java:122) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.event.internal.DefaultPersistEventListener.entityIsTransient(DefaultPersistEventListener.java:185) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:128) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.event.internal.DefaultPersistEventListener.onPersist(DefaultPersistEventListener.java:55) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.event.service.internal.EventListenerGroupImpl.fireEventOnEachListener(EventListenerGroupImpl.java:107) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.internal.SessionImpl.firePersist(SessionImpl.java:756) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at org.hibernate.internal.SessionImpl.persist(SessionImpl.java:742) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[na:na]
        at org.springframework.orm.jpa.SharedEntityManagerCreator$SharedEntityManagerInvocationHandler.invoke(SharedEntityManagerCreator.java:315) ~[spring-orm-5.3.31.jar!/:5.3.31]
        at jdk.proxy2/jdk.proxy2.$Proxy197.persist(Unknown Source) ~[na:na]
        at org.springframework.data.jpa.repository.support.SimpleJpaRepository.save(SimpleJpaRepository.java:666) ~[spring-data-jpa-2.7.18.jar!/:2.7.18]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:104) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:578) ~[na:na]
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker$RepositoryFragmentMethodInvoker.lambda$new$0(RepositoryMethodInvoker.java:289) ~[spring-data-commons-2.7.18.jar!/:2.7.18]
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.doInvoke(RepositoryMethodInvoker.java:137) ~[spring-data-commons-2.7.18.jar!/:2.7.18]
        at org.springframework.data.repository.core.support.RepositoryMethodInvoker.invoke(RepositoryMethodInvoker.java:121) ~[spring-data-commons-2.7.18.jar!/:2.7.18]
        at org.springframework.data.repository.core.support.RepositoryComposition$RepositoryFragments.invoke(RepositoryComposition.java:530) ~[spring-data-commons-2.7.18.jar!/:2.7.18]
        at org.springframework.data.repository.core.support.RepositoryComposition.invoke(RepositoryComposition.java:286) ~[spring-data-commons-2.7.18.jar!/:2.7.18]
        at org.springframework.data.repository.core.support.RepositoryFactorySupport$ImplementationMethodExecutionInterceptor.invoke(RepositoryFactorySupport.java:640) ~[spring-data-commons-2.7.18.jar!/:2.7.18]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.31.jar!/:5.3.31]
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.doInvoke(QueryExecutorMethodInterceptor.java:164) ~[spring-data-commons-2.7.18.jar!/:2.7.18]
        at org.springframework.data.repository.core.support.QueryExecutorMethodInterceptor.invoke(QueryExecutorMethodInterceptor.java:139) ~[spring-data-commons-2.7.18.jar!/:2.7.18]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.31.jar!/:5.3.31]
        at org.springframework.data.projection.DefaultMethodInvokingMethodInterceptor.invoke(DefaultMethodInvokingMethodInterceptor.java:76) ~[spring-data-commons-2.7.18.jar!/:2.7.18]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.31.jar!/:5.3.31]
        at org.springframework.transaction.interceptor.TransactionInterceptor$1.proceedWithInvocation(TransactionInterceptor.java:123) ~[spring-tx-5.3.31.jar!/:5.3.31]
        at org.springframework.transaction.interceptor.TransactionAspectSupport.invokeWithinTransaction(TransactionAspectSupport.java:388) ~[spring-tx-5.3.31.jar!/:5.3.31]
        at org.springframework.transaction.interceptor.TransactionInterceptor.invoke(TransactionInterceptor.java:119) ~[spring-tx-5.3.31.jar!/:5.3.31]
        at org.springframework.aop.framework.ReflectiveMethodInvocation.proceed(ReflectiveMethodInvocation.java:186) ~[spring-aop-5.3.31.jar!/:5.3.31]
        at org.springframework.dao.support.PersistenceExceptionTranslationInterceptor.invoke(PersistenceExceptionTranslationInterceptor.java:137) ~[spring-tx-5.3.31.jar!/:5.3.31]
        ... 22 common frames omitted
Caused by: java.sql.SQLIntegrityConstraintViolationException: integrity constraint violation: unique constraint or index violation: IDX_ARTIST_NAME
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
        at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
        at org.hsqldb.jdbc.JDBCPreparedStatement.fetchResult(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
        at org.hsqldb.jdbc.JDBCPreparedStatement.executeUpdate(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
        at com.zaxxer.hikari.pool.ProxyPreparedStatement.executeUpdate(ProxyPreparedStatement.java:61) ~[HikariCP-4.0.3.jar!/:na]
        at com.zaxxer.hikari.pool.HikariProxyPreparedStatement.executeUpdate(HikariProxyPreparedStatement.java) ~[HikariCP-4.0.3.jar!/:na]
        at org.hibernate.engine.jdbc.internal.ResultSetReturnImpl.executeUpdate(ResultSetReturnImpl.java:197) ~[hibernate-core-5.6.15.Final.jar!/:5.6.15.Final]
        ... 65 common frames omitted
Caused by: org.hsqldb.HsqlException: integrity constraint violation: unique constraint or index violation: IDX_ARTIST_NAME
        at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
        at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
        at org.hsqldb.index.IndexAVL.insert(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
        at org.hsqldb.persist.RowStoreAVL.indexRow(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
        at org.hsqldb.persist.RowStoreAVLDisk.indexRow(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
        at org.hsqldb.TransactionManagerMVCC.addInsertAction(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
        at org.hsqldb.Session.addInsertAction(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
        at org.hsqldb.Table.insertSingleRow(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
        at org.hsqldb.StatementDML.insertRowSet(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
        at org.hsqldb.StatementInsert.getResult(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
        at org.hsqldb.StatementDMQL.execute(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
        at org.hsqldb.Session.executeCompiledStatement(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
        at org.hsqldb.Session.execute(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
        ... 70 common frames omitted

2024-05-01 21:34:09.022  INFO --- o.a.p.s.MediaScannerService              : Media library scan took 656s
2024-05-01 21:34:09.022  INFO --- o.a.p.s.MediaScannerService              : Media library scan completed.
2024-05-01 21:34:09.023  INFO --- o.a.p.service.PlaylistService            : Starting playlist import.
2024-05-01 21:34:09.023  INFO --- o.a.p.service.PlaylistService            : Completed playlist import.
```

**Comment by yuygfgg** [comment]
They show up correctly in folder view, but not in album view. So I think something's wrong with apis related to albums.

**Comment by kagemomiji** [comment]
@yuygfgg 
This issue appears to be the same as issue https://github.com/kagemomiji/airsonic-advanced/issues/392.
Could you try the latest edge-release?

**Comment by yuygfgg** [comment]
> @yuygfgg This issue appears to be the same as issue #392. Could you try the latest edge-release?

Thank you a lot! It's working smoothly now
