### ISSUE TITLE
When upgrading from old airsonic (10.6.0 according to META-INF/MANIFEST.MF) 11.1.3 crashes with liquibase.exception.MigrationFailedException

### ISSUE THREAD

**Issue by mcepl** [kagemomiji/airsonic-advanced#499]
### What happened?

The start of the server failed with the error shown below.

### Steps to reproduce

Database migrated via the method described in https://github.com/kagemomiji/airsonic-advanced/issues/151#issuecomment-1474311251 .

### Version

11.1.3 (Stable)

### Operating System

Linux (OpenSUSE/Leap 15.5)

### Java Version

openjdk version "17.0.11" 2024-04-16

### Database

Other

### DB Detail

default hsqldb I believe

### Configuration paramter

Not sure what you exactly want, running airsonic from systemctl via provided `airsonic.service` (refreshed from Git today).

### language

None

### Relevant log output

```console
Jun 12 08:38:53 narcis java[24644]:            _                       _
Jun 12 08:38:53 narcis java[24644]:      /\   (_)                     (_)
Jun 12 08:38:53 narcis java[24644]:     /  \   _ _ __  ___  ___  _ __  _  ___
Jun 12 08:38:53 narcis java[24644]:    / /\ \ | | '__|/ __|/ _ \| '_ \| |/ __|
Jun 12 08:38:53 narcis java[24644]:   / ____ \| | |   \__ \ (_) | | | | | (__
Jun 12 08:38:53 narcis java[24644]:  /_/    \_\_|_|   |___/\___/|_| |_|_|\___|
Jun 12 08:38:53 narcis java[24644]:                                                
Jun 12 08:38:53 narcis java[24644]:                         11.1.3
Jun 12 08:38:53 narcis java[24644]: 2024-06-12 08:38:53.983  WARN --- o.a.p.u.LegacyHsqlMigrationUtil          : HSQLDB database upgrade needed, from version 2.5.0 to 2.7
Jun 12 08:38:53 narcis java[24644]: 2024-06-12 08:38:53.991  INFO --- o.a.p.u.LegacyHsqlMigrationUtil          : HSQLDB database backed up to /var/airsonic/backups/db.backup.20240612083853
Jun 12 08:38:54 narcis java[24644]: 2024-06-12 08:38:54.724  INFO --- o.a.p.u.LegacyHsqlMigrationUtil          : HSQLDB database has been upgraded
Jun 12 08:38:54 narcis java[24644]: 2024-06-12 08:38:54.726  INFO --- o.a.p.u.LegacyHsqlMigrationUtil          : HSQLDB database version is now 2.7.1
Jun 12 08:38:54 narcis java[24644]: 2024-06-12 08:38:54.738  INFO --- org.airsonic.player.Application          : Starting Application v11.1.3 using Java 17.0.11 on narcis with PID 24644 (/var/airsonic/airsonic.war started by airsonic in /)
Jun 12 08:38:54 narcis java[24644]: 2024-06-12 08:38:54.741  INFO --- org.airsonic.player.Application          : No active profile set, falling back to 1 default profile: "default"
Jun 12 08:38:58 narcis java[24644]: 2024-06-12 08:38:58.689  INFO --- o.a.p.service.SettingsService            : Java: 17.0.11+9-suse-150400.3.42.1-x8664, OS: Linux, Memory (max bytes): 734003200
Jun 12 08:38:58 narcis java[24644]: 2024-06-12 08:38:58.838  INFO --- org.airsonic.player.Application          : Detected Tomcat web server
Jun 12 08:39:05 narcis java[24644]: 2024-06-12 08:39:05.538  INFO --- l.database.core.HsqlDatabase             : Set default schema name to PUBLIC
Jun 12 08:39:05 narcis java[24644]: 2024-06-12 08:39:05.688  INFO --- l.l.StandardLockService                  : Successfully acquired change log lock
Jun 12 08:39:06 narcis java[24644]: 2024-06-12 08:39:06.804  INFO --- liquibase.Liquibase                      : Parsed changelog file 'classpath:liquibase/db-changelog.xml'
Jun 12 08:39:06 narcis java[24644]: 2024-06-12 08:39:06.835  INFO --- l.c.StandardChangeLogHistoryService      : Creating database history table with name: PUBLIC.DATABASECHANGELOG
Jun 12 08:39:07 narcis java[24644]: 2024-06-12 08:39:07.799  INFO --- l.l.StandardLockService                  : Successfully released change log lock
Jun 12 08:39:07 narcis java[24644]: 2024-06-12 08:39:07.917  INFO --- l.l.StandardLockService                  : Successfully acquired change log lock
Jun 12 08:39:08 narcis java[24644]: 2024-06-12 08:39:08.496  INFO --- l.c.StandardChangeLogHistoryService      : Creating database history table with name: PUBLIC.DATABASECHANGELOG
Jun 12 08:39:08 narcis java[24644]: 2024-06-12 08:39:08.499  INFO --- l.c.StandardChangeLogHistoryService      : Reading from PUBLIC.DATABASECHANGELOG
Jun 12 08:39:08 narcis java[24644]: 2024-06-12 08:39:08.652  INFO --- l.command.core.UpdateCommandStep         : Using deploymentId: 8174348502
Jun 12 08:39:08 narcis java[24644]: 2024-06-12 08:39:08.688  INFO --- l.c.StandardChangeLogHistoryService      : Reading from PUBLIC.DATABASECHANGELOG
Jun 12 08:39:08 narcis java[24644]: Running Changeset: liquibase/legacy/schema25.xml::schema25_002::muff1nman
Jun 12 08:39:08 narcis java[24644]: 2024-06-12 08:39:08.835  INFO --- liquibase.changelog.ChangeSet            : Table version created
Jun 12 08:39:08 narcis java[24644]: 2024-06-12 08:39:08.836  INFO --- liquibase.changelog.ChangeSet            : New row inserted into version
Jun 12 08:39:08 narcis java[24644]: 2024-06-12 08:39:08.836  INFO --- liquibase.changelog.ChangeSet            : ChangeSet liquibase/legacy/schema25.xml::schema25_002::muff1nman ran successfully in 25ms
Jun 12 08:39:08 narcis java[24644]: Running Changeset: liquibase/legacy/schema25.xml::schema25_003::muff1nman
Jun 12 08:39:08 narcis java[24644]: 2024-06-12 08:39:08.848 ERROR --- liquibase.changelog.ChangeSet            : ChangeSet liquibase/legacy/schema25.xml::schema25_003::muff1nman encountered an exception.
Jun 12 08:39:08 narcis java[24644]: 2024-06-12 08:39:08.850  INFO --- l.command.core.UpdateCommandStep         : Update command encountered an exception.
Jun 12 08:39:08 narcis java[24644]: 2024-06-12 08:39:08.851  INFO --- l.l.StandardLockService                  : Successfully released change log lock
Jun 12 08:39:08 narcis java[24644]: 2024-06-12 08:39:08.852  INFO --- l.l.StandardLockService                  : Successfully released change log lock
Jun 12 08:39:08 narcis java[24644]: 2024-06-12 08:39:08.853  INFO --- liquibase.command.CommandScope           : Command execution complete
Jun 12 08:39:08 narcis java[24644]: 2024-06-12 08:39:08.858  WARN --- ConfigServletWebServerApplicationContext : Exception encountered during context initialization - cancelling refresh attempt: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset liquibase/legacy/schema25.xml::schema25_003::muff1nman:
Jun 12 08:39:08 narcis java[24644]:      Reason: liquibase.exception.DatabaseException: length must be specified in type definition: VARCHAR [Failed SQL: (-5599) CREATE TABLE PUBLIC."ROLE" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR NOT NULL, CONSTRAINT PK_ROLE PRIMARY KEY (id))]
Jun 12 08:39:09 narcis java[24644]: 2024-06-12 08:39:09.277 ERROR --- o.s.boot.SpringApplication               : Application run failed
Jun 12 08:39:09 narcis java[24644]: org.springframework.beans.factory.BeanCreationException: Error creating bean with name 'liquibase' defined in class path resource [org/springframework/boot/autoconfigure/liquibase/LiquibaseAutoConfiguration$LiquibaseConfiguration.class]: Invocation of init method failed; nested exception is liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset liquibase/legacy/schema25.xml::schema25_003::muff1nman:
Jun 12 08:39:09 narcis java[24644]:      Reason: liquibase.exception.DatabaseException: length must be specified in type definition: VARCHAR [Failed SQL: (-5599) CREATE TABLE PUBLIC."ROLE" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR NOT NULL, CONSTRAINT PK_ROLE PRIMARY KEY (id))]
Jun 12 08:39:09 narcis java[24644]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1804) ~[spring-beans-5.3.31.jar!/:5.3.31]
Jun 12 08:39:09 narcis java[24644]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.doCreateBean(AbstractAutowireCapableBeanFactory.java:620) ~[spring-beans-5.3.31.jar!/:5.3.31]
Jun 12 08:39:09 narcis java[24644]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.createBean(AbstractAutowireCapableBeanFactory.java:542) ~[spring-beans-5.3.31.jar!/:5.3.31]
Jun 12 08:39:09 narcis java[24644]:         at org.springframework.beans.factory.support.AbstractBeanFactory.lambda$doGetBean$0(AbstractBeanFactory.java:335) ~[spring-beans-5.3.31.jar!/:5.3.31]
Jun 12 08:39:09 narcis java[24644]:         at org.springframework.beans.factory.support.DefaultSingletonBeanRegistry.getSingleton(DefaultSingletonBeanRegistry.java:234) ~[spring-beans-5.3.31.jar!/:5.3.31]
Jun 12 08:39:09 narcis java[24644]:         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:333) ~[spring-beans-5.3.31.jar!/:5.3.31]
Jun 12 08:39:09 narcis java[24644]:         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.31.jar!/:5.3.31]
Jun 12 08:39:09 narcis java[24644]:         at org.springframework.beans.factory.support.AbstractBeanFactory.doGetBean(AbstractBeanFactory.java:322) ~[spring-beans-5.3.31.jar!/:5.3.31]
Jun 12 08:39:09 narcis java[24644]:         at org.springframework.beans.factory.support.AbstractBeanFactory.getBean(AbstractBeanFactory.java:208) ~[spring-beans-5.3.31.jar!/:5.3.31]
Jun 12 08:39:09 narcis java[24644]:         at org.springframework.context.support.AbstractApplicationContext.getBean(AbstractApplicationContext.java:1168) ~[spring-context-5.3.31.jar!/:5.3.31]
Jun 12 08:39:09 narcis java[24644]:         at org.springframework.context.support.AbstractApplicationContext.finishBeanFactoryInitialization(AbstractApplicationContext.java:919) ~[spring-context-5.3.31.jar!/:5.3.31]
Jun 12 08:39:09 narcis java[24644]:         at org.springframework.context.support.AbstractApplicationContext.refresh(AbstractApplicationContext.java:591) ~[spring-context-5.3.31.jar!/:5.3.31]
Jun 12 08:39:09 narcis java[24644]:         at org.springframework.boot.web.servlet.context.ServletWebServerApplicationContext.refresh(ServletWebServerApplicationContext.java:147) ~[spring-boot-2.7.18.jar!/:2.7.18]
Jun 12 08:39:09 narcis java[24644]:         at org.springframework.boot.SpringApplication.refresh(SpringApplication.java:732) ~[spring-boot-2.7.18.jar!/:2.7.18]
Jun 12 08:39:09 narcis java[24644]:         at org.springframework.boot.SpringApplication.refreshContext(SpringApplication.java:409) ~[spring-boot-2.7.18.jar!/:2.7.18]
Jun 12 08:39:09 narcis java[24644]:         at org.springframework.boot.SpringApplication.run(SpringApplication.java:308) ~[spring-boot-2.7.18.jar!/:2.7.18]
Jun 12 08:39:09 narcis java[24644]:         at org.springframework.boot.builder.SpringApplicationBuilder.run(SpringApplicationBuilder.java:164) ~[spring-boot-2.7.18.jar!/:2.7.18]
Jun 12 08:39:09 narcis java[24644]:         at org.airsonic.player.Application.main(Application.java:70) ~[classes!/:11.1.3]
Jun 12 08:39:09 narcis java[24644]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[na:na]
Jun 12 08:39:09 narcis java[24644]:         at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[na:na]
Jun 12 08:39:09 narcis java[24644]:         at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[na:na]
Jun 12 08:39:09 narcis java[24644]:         at java.base/java.lang.reflect.Method.invoke(Method.java:568) ~[na:na]
Jun 12 08:39:09 narcis java[24644]:         at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:49) ~[airsonic.war:11.1.3]
Jun 12 08:39:09 narcis java[24644]:         at org.springframework.boot.loader.Launcher.launch(Launcher.java:108) ~[airsonic.war:11.1.3]
Jun 12 08:39:09 narcis java[24644]:         at org.springframework.boot.loader.Launcher.launch(Launcher.java:58) ~[airsonic.war:11.1.3]
Jun 12 08:39:09 narcis java[24644]:         at org.springframework.boot.loader.WarLauncher.main(WarLauncher.java:59) ~[airsonic.war:11.1.3]
Jun 12 08:39:09 narcis java[24644]: Caused by: liquibase.exception.CommandExecutionException: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset liquibase/legacy/schema25.xml::schema25_003::muff1nman:
Jun 12 08:39:09 narcis java[24644]:      Reason: liquibase.exception.DatabaseException: length must be specified in type definition: VARCHAR [Failed SQL: (-5599) CREATE TABLE PUBLIC."ROLE" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR NOT NULL, CONSTRAINT PK_ROLE PRIMARY KEY (id))]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.command.CommandScope.execute(CommandScope.java:235) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Liquibase.lambda$update$0(Liquibase.java:237) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Scope.lambda$child$0(Scope.java:194) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Scope.child(Scope.java:203) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Scope.child(Scope.java:193) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Scope.child(Scope.java:172) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Liquibase.runInScope(Liquibase.java:1605) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Liquibase.update(Liquibase.java:229) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Liquibase.update(Liquibase.java:213) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.integration.spring.SpringLiquibase.performUpdate(SpringLiquibase.java:329) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.integration.spring.SpringLiquibase.afterPropertiesSet(SpringLiquibase.java:284) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.invokeInitMethods(AbstractAutowireCapableBeanFactory.java:1863) ~[spring-beans-5.3.31.jar!/:5.3.31]
Jun 12 08:39:09 narcis java[24644]:         at org.springframework.beans.factory.support.AbstractAutowireCapableBeanFactory.initializeBean(AbstractAutowireCapableBeanFactory.java:1800) ~[spring-beans-5.3.31.jar!/:5.3.31]
Jun 12 08:39:09 narcis java[24644]:         ... 25 common frames omitted
Jun 12 08:39:09 narcis java[24644]: Caused by: liquibase.exception.LiquibaseException: liquibase.exception.MigrationFailedException: Migration failed for changeset liquibase/legacy/schema25.xml::schema25_003::muff1nman:
Jun 12 08:39:09 narcis java[24644]:      Reason: liquibase.exception.DatabaseException: length must be specified in type definition: VARCHAR [Failed SQL: (-5599) CREATE TABLE PUBLIC."ROLE" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR NOT NULL, CONSTRAINT PK_ROLE PRIMARY KEY (id))]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:121) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.command.core.AbstractUpdateCommandStep.lambda$run$0(AbstractUpdateCommandStep.java:103) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Scope.lambda$child$0(Scope.java:194) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Scope.child(Scope.java:203) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Scope.child(Scope.java:193) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Scope.child(Scope.java:172) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.command.core.AbstractUpdateCommandStep.run(AbstractUpdateCommandStep.java:100) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.command.CommandScope.execute(CommandScope.java:212) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         ... 37 common frames omitted
Jun 12 08:39:09 narcis java[24644]: Caused by: liquibase.exception.MigrationFailedException: Migration failed for changeset liquibase/legacy/schema25.xml::schema25_003::muff1nman:
Jun 12 08:39:09 narcis java[24644]:      Reason: liquibase.exception.DatabaseException: length must be specified in type definition: VARCHAR [Failed SQL: (-5599) CREATE TABLE PUBLIC."ROLE" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR NOT NULL, CONSTRAINT PK_ROLE PRIMARY KEY (id))]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.changelog.ChangeSet.execute(ChangeSet.java:759) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.changelog.visitor.UpdateVisitor.visit(UpdateVisitor.java:61) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.changelog.ChangeLogIterator$2.lambda$null$0(ChangeLogIterator.java:109) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Scope.lambda$child$0(Scope.java:194) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Scope.child(Scope.java:203) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Scope.child(Scope.java:193) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Scope.child(Scope.java:172) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.changelog.ChangeLogIterator$2.lambda$run$1(ChangeLogIterator.java:109) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Scope.lambda$child$0(Scope.java:194) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Scope.child(Scope.java:203) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Scope.child(Scope.java:193) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Scope.child(Scope.java:172) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Scope.child(Scope.java:260) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.changelog.ChangeLogIterator$2.run(ChangeLogIterator.java:92) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Scope.lambda$child$0(Scope.java:194) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Scope.child(Scope.java:203) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Scope.child(Scope.java:193) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Scope.child(Scope.java:172) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Scope.child(Scope.java:260) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.Scope.child(Scope.java:264) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.changelog.ChangeLogIterator.run(ChangeLogIterator.java:66) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         ... 44 common frames omitted
Jun 12 08:39:09 narcis java[24644]: Caused by: liquibase.exception.DatabaseException: length must be specified in type definition: VARCHAR [Failed SQL: (-5599) CREATE TABLE PUBLIC."ROLE" (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, name VARCHAR NOT NULL, CONSTRAINT PK_ROLE PRIMARY KEY (id))]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:445) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:77) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.executor.jvm.JdbcExecutor.execute(JdbcExecutor.java:160) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.database.AbstractJdbcDatabase.execute(AbstractJdbcDatabase.java:1287) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.database.AbstractJdbcDatabase.executeStatements(AbstractJdbcDatabase.java:1269) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.changelog.ChangeSet.execute(ChangeSet.java:717) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         ... 64 common frames omitted
Jun 12 08:39:09 narcis java[24644]: Caused by: java.sql.SQLSyntaxErrorException: length must be specified in type definition: VARCHAR
Jun 12 08:39:09 narcis java[24644]:         at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
Jun 12 08:39:09 narcis java[24644]:         at org.hsqldb.jdbc.JDBCUtil.sqlException(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
Jun 12 08:39:09 narcis java[24644]:         at org.hsqldb.jdbc.JDBCStatement.fetchResult(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
Jun 12 08:39:09 narcis java[24644]:         at org.hsqldb.jdbc.JDBCStatement.execute(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
Jun 12 08:39:09 narcis java[24644]:         at com.zaxxer.hikari.pool.ProxyStatement.execute(ProxyStatement.java:94) ~[HikariCP-4.0.3.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at com.zaxxer.hikari.pool.HikariProxyStatement.execute(HikariProxyStatement.java) ~[HikariCP-4.0.3.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         at liquibase.executor.jvm.JdbcExecutor$ExecuteStatementCallback.doInStatement(JdbcExecutor.java:441) ~[liquibase-core-4.22.0.jar!/:na]
Jun 12 08:39:09 narcis java[24644]:         ... 69 common frames omitted
Jun 12 08:39:09 narcis java[24644]: Caused by: org.hsqldb.HsqlException: length must be specified in type definition: VARCHAR
Jun 12 08:39:09 narcis java[24644]:         at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
Jun 12 08:39:09 narcis java[24644]:         at org.hsqldb.error.Error.error(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
Jun 12 08:39:09 narcis java[24644]:         at org.hsqldb.ParserDQL.readTypeDefinition(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
Jun 12 08:39:09 narcis java[24644]:         at org.hsqldb.ParserTable.readColumnDefinitionOrNull(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
Jun 12 08:39:09 narcis java[24644]:         at org.hsqldb.ParserTable.readTableContentsSource(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
Jun 12 08:39:09 narcis java[24644]:         at org.hsqldb.ParserTable.compileCreateTableBody(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
Jun 12 08:39:09 narcis java[24644]:         at org.hsqldb.ParserTable.compileCreateTable(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
Jun 12 08:39:09 narcis java[24644]:         at org.hsqldb.ParserDDL.compileCreate(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
Jun 12 08:39:09 narcis java[24644]:         at org.hsqldb.ParserCommand.compilePart(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
Jun 12 08:39:09 narcis java[24644]:         at org.hsqldb.ParserCommand.compileStatements(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
Jun 12 08:39:09 narcis java[24644]:         at org.hsqldb.Session.executeDirectStatement(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
Jun 12 08:39:09 narcis java[24644]:         at org.hsqldb.Session.execute(Unknown Source) ~[hsqldb-2.7.1.jar!/:2.7.1]
Jun 12 08:39:09 narcis java[24644]:         ... 74 common frames omitted
```

**Comment by kagemomiji** [comment]
@mcepl 
would like to know if you upgraded following these steps:

airsonic 10.6.2 -> kagemomiji's airsonic-advanced: edge-11.0.0-SNAPSHOT.20221224143241 -> kagemomiji's airsonic-advanced latest-release.
[reference](https://github.com/kagemomiji/airsonic-advanced#11x-series)

From your logs, it appears that the migration executed on the intermediate edge-11.0.0-SNAPSHOT.20221224143241 is running on the latest release.

**Comment by mcepl** [comment]
Yes, I tried that, but I am afraid that my settings are now hopelessly messed up now, so I won’t be able to help with this ticket any more.
