### ISSUE TITLE
[Bug]: Failed to get/parse RSS file for Podcast channel 

### ISSUE THREAD

**Issue by John9026231** [kagemomiji/airsonic-advanced#613]
### What happened?

After adding Podcast RSS feed, the Podcasts will load/download correctly on the first run. Any subsequent updates result in Failed to get/parse RSS file.

```
2024-09-30 19:20:48.269  WARN --- o.a.p.s.podcast.PodcastRefresher         : Failed to get/parse RSS file for Podcast channel https://www.google.com/url?q=https://anchor.fm/s/1f9996c4/podcast/rss&sa=U&ved=2ahUKEwjVqZCw1qjyAhX7Q_EDHXxGDiwQFnoECAUQAQ&usg=AOvVaw2NwaAVkjwikgxlEtxRIpFQ

java.net.UnknownHostException: www.google.com
	at java.base/java.net.InetAddress$CachedAddresses.get(Unknown Source) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName0(Unknown Source) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName(Unknown Source) ~[na:na]
	at java.base/java.net.InetAddress.getAllByName(Unknown Source) ~[na:na]
	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[httpclient-4.5.14.jar:4.5.14]
	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112) ~[httpclient-4.5.14.jar:4.5.14]
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.14.jar:4.5.14]
	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.14.jar:4.5.14]
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.14.jar:4.5.14]
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.14.jar:4.5.14]
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.14.jar:4.5.14]
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.14.jar:4.5.14]
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.14.jar:4.5.14]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.14.jar:4.5.14]
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.14.jar:4.5.14]
	at org.airsonic.player.service.podcast.PodcastRefresher.refresh_aroundBody0(PodcastRefresher.java:104) ~[classes/:na]
	at org.airsonic.player.service.podcast.PodcastRefresher$AjcClosure1.run(PodcastRefresher.java:1) ~[classes/:na]
	at org.springframework.scheduling.aspectj.AbstractAsyncExecutionAspect.ajc$around$org_springframework_scheduling_aspectj_AbstractAsyncExecutionAspect$1$6c004c3eproceed(AbstractAsyncExecutionAspect.aj:65) ~[spring-aspects-6.1.13.jar:6.1.13]
	at org.springframework.scheduling.aspectj.AbstractAsyncExecutionAspect$AbstractAsyncExecutionAspect$1.call(AbstractAsyncExecutionAspect.aj:76) ~[spring-aspects-6.1.13.jar:6.1.13]
	at org.springframework.util.concurrent.FutureUtils.lambda$toSupplier$0(FutureUtils.java:74) ~[spring-core-6.1.13.jar:6.1.13]
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]
	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

### Steps to reproduce

1. Add Podcast RSS feed
2.  Wait a day(?) or Restart container(?)
3.  Unable to Parse 

### Version

11.1.4 (Stable)

### Operating System

Ubuntu 24.04.1 LTS

### Java Version

jdk-17.0.10+7

### Database

Other

### DB Detail

HSQL

### Configuration paramter

unknown 

### language

None

**Comment by kagemomiji** [comment]
@John9026231 
It seems like the hostname for www.google.com cannot be resolved due to an error. Is it possible to access www.google.com from the machine where Airsonic Advanced is running?
Also, if you could share the RSS URL, I can test it on my end, which might help in resolving the issue.

**Comment by John9026231** [comment]
Thanks for following up. I can, its on the machine I am currently on, no issues. 

Please find the below.

https://podcastaddict.com/podcast/forehead-fables/3577385

To also note, this is also applicable to a Patreon podcast I run into. Sharing the error message with redacted information because its subscription based. 

After restarting the container, issues subside it appears. 


```
2024-10-08 01:55:36.228  WARN --- o.a.p.s.podcast.PodcastRefresher         : Failed to get/parse RSS file for Podcast channel https://www.patreon.com/rss/level1?auth=XXXXXXXXXXXXXXXXX

java.net.UnknownHostException: www.patreon.com: Temporary failure in name resolution

	at java.base/java.net.Inet6AddressImpl.lookupAllHostAddr(Native Method) ~[na:na]

	at java.base/java.net.InetAddress$PlatformNameService.lookupAllHostAddr(Unknown Source) ~[na:na]

	at java.base/java.net.InetAddress.getAddressesFromNameService(Unknown Source) ~[na:na]

	at java.base/java.net.InetAddress$NameServiceAddresses.get(Unknown Source) ~[na:na]

	at java.base/java.net.InetAddress.getAllByName0(Unknown Source) ~[na:na]

	at java.base/java.net.InetAddress.getAllByName(Unknown Source) ~[na:na]

	at java.base/java.net.InetAddress.getAllByName(Unknown Source) ~[na:na]

	at org.apache.http.impl.conn.SystemDefaultDnsResolver.resolve(SystemDefaultDnsResolver.java:45) ~[httpclient-4.5.14.jar:4.5.14]

	at org.apache.http.impl.conn.DefaultHttpClientConnectionOperator.connect(DefaultHttpClientConnectionOperator.java:112) ~[httpclient-4.5.14.jar:4.5.14]

	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.connect(PoolingHttpClientConnectionManager.java:376) ~[httpclient-4.5.14.jar:4.5.14]

	at org.apache.http.impl.execchain.MainClientExec.establishRoute(MainClientExec.java:393) ~[httpclient-4.5.14.jar:4.5.14]

	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:236) ~[httpclient-4.5.14.jar:4.5.14]

	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:186) ~[httpclient-4.5.14.jar:4.5.14]

	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89) ~[httpclient-4.5.14.jar:4.5.14]

	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:110) ~[httpclient-4.5.14.jar:4.5.14]

	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185) ~[httpclient-4.5.14.jar:4.5.14]

	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:83) ~[httpclient-4.5.14.jar:4.5.14]

	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:108) ~[httpclient-4.5.14.jar:4.5.14]

	at org.airsonic.player.service.podcast.PodcastRefresher.refresh_aroundBody0(PodcastRefresher.java:104) ~[classes/:na]

	at org.airsonic.player.service.podcast.PodcastRefresher$AjcClosure1.run(PodcastRefresher.java:1) ~[classes/:na]

	at org.springframework.scheduling.aspectj.AbstractAsyncExecutionAspect.ajc$around$org_springframework_scheduling_aspectj_AbstractAsyncExecutionAspect$1$6c004c3eproceed(AbstractAsyncExecutionAspect.aj:65) ~[spring-aspects-6.1.13.jar:6.1.13]

	at org.springframework.scheduling.aspectj.AbstractAsyncExecutionAspect$AbstractAsyncExecutionAspect$1.call(AbstractAsyncExecutionAspect.aj:76) ~[spring-aspects-6.1.13.jar:6.1.13]

	at org.springframework.util.concurrent.FutureUtils.lambda$toSupplier$0(FutureUtils.java:74) ~[spring-core-6.1.13.jar:6.1.13]

	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(Unknown Source) ~[na:na]

	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source) ~[na:na]

	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source) ~[na:na]

	at java.base/java.lang.Thread.run(Unknown Source) ~[na:na]
```

**Comment by John9026231** [comment]
Is there a function to ping an address within the container? Ping isnt a function from the command line.
