### ISSUE TITLE
[Bug]: All playlists are empty

### ISSUE THREAD

**Issue by produnis** [kagemomiji/airsonic-advanced#662]
### What happened?

Hi there, I am on 11.1.5-SNAPSHOT.20241230112630, and all my playlists seem to be empty. 

![While it says, that 41 songs are in the list, the paylist itself is empty](https://i.imgur.com/Am0bymB.jpeg)

While it says, that 41 songs are in the list, the paylist itself is empty

On my apps like "Ultrasonic", it states 
`"failed to lazily initialize a collection ..."`

### Steps to reproduce

1. create a new playlist
2. Add some songs to the list
3. go to tab "playlists"
4. See that the list is empty

### Version

11.1.5-SNAPSHOT (Edge)

### Version Detail

11.1.5-SNAPSHOT.20241230112630

### Operating System

archlinux

### Java Version

java-23-openjdk

### Database

Other

### DB Detail

airsonic default

### Configuration paramter

# Change the port to listen on
PORT=4040

# Change the path that is listened on
CONTEXT_PATH=/airsonic

### language

German

**Comment by produnis** [comment]
this is in logs:

```
ERROR --- .WebSocketAnnotationMethodMessageHandler : Unhandled exception from message handler method

org.hibernate.LazyInitializationException: failed to lazily initialize a collection of role: org.airsonic.player.domain.Playlist.mediaFiles: could not initialize proxy - no Session
        at org.hibernate.collection.spi.AbstractPersistentCollection.throwLazyInitializationException(AbstractPersistentCollection.java:636) ~[hibernate-core-6.5.3.Final.jar!/:6.5.3.Final]
        at org.hibernate.collection.spi.AbstractPersistentCollection.withTemporarySessionIfNeeded(AbstractPersistentCollection.java:219) ~[hibernate-core-6.5.3.Final.jar!/:6.5.3.Final]
        at org.hibernate.collection.spi.AbstractPersistentCollection.initialize(AbstractPersistentCollection.java:615) ~[hibernate-core-6.5.3.Final.jar!/:6.5.3.Final]
        at org.hibernate.collection.spi.AbstractPersistentCollection.read(AbstractPersistentCollection.java:138) ~[hibernate-core-6.5.3.Final.jar!/:6.5.3.Final]
        at org.hibernate.collection.spi.PersistentBag.iterator(PersistentBag.java:369) ~[hibernate-core-6.5.3.Final.jar!/:6.5.3.Final]
        at java.base/java.util.Spliterators$IteratorSpliterator.estimateSize(Spliterators.java:1959) ~[na:na]
        at java.base/java.util.Spliterator.getExactSizeIfKnown(Spliterator.java:414) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyIntoWithCancel(AbstractPipeline.java:587) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:574) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:560) ~[na:na]
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:921) ~[na:na]
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:265) ~[na:na]
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:727) ~[na:na]
        at org.airsonic.player.service.PlaylistService.setFilesInPlaylist(PlaylistService.java:185) ~[!/:11.1.5-SNAPSHOT]
        at org.airsonic.player.service.PlaylistService.lambda$setFilesInPlaylist$7(PlaylistService.java:170) ~[!/:11.1.5-SNAPSHOT]
        at java.base/java.util.Optional.map(Optional.java:260) ~[na:na]
        at org.airsonic.player.service.PlaylistService.setFilesInPlaylist(PlaylistService.java:169) ~[!/:11.1.5-SNAPSHOT]
        at org.airsonic.player.ajax.PlaylistWSController.createPlaylistForPlayQueue(PlaylistWSController.java:115) ~[!/:11.1.5-SNAPSHOT]
        at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103) ~[na:na]
        at java.base/java.lang.reflect.Method.invoke(Method.java:580) ~[na:na]
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.doInvoke(InvocableHandlerMethod.java:169) ~[spring-messaging-6.1.15.jar!/:6.1.15]
        at org.springframework.messaging.handler.invocation.InvocableHandlerMethod.invoke(InvocableHandlerMethod.java:119) ~[spring-messaging-6.1.15.jar!/:6.1.15]
        at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMatch(AbstractMethodMessageHandler.java:567) ~[spring-messaging-6.1.15.jar!/:6.1.15]
        at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:529) ~[spring-messaging-6.1.15.jar!/:6.1.15]
        at org.springframework.messaging.simp.annotation.support.SimpAnnotationMethodMessageHandler.handleMatch(SimpAnnotationMethodMessageHandler.java:93) ~[spring-messaging-6.1.15.jar!/:6.1.15]
        at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessageInternal(AbstractMethodMessageHandler.java:522) ~[spring-messaging-6.1.15.jar!/:6.1.15]
        at org.springframework.messaging.handler.invocation.AbstractMethodMessageHandler.handleMessage(AbstractMethodMessageHandler.java:457) ~[spring-messaging-6.1.15.jar!/:6.1.15]
        at org.springframework.messaging.support.ExecutorSubscribableChannel$SendTask.run(ExecutorSubscribableChannel.java:152) ~[spring-messaging-6.1.15.jar!/:6.1.15]
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144) ~[na:na]
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642) ~[na:na]
        at java.base/java.lang.Thread.run(Thread.java:1575) ~[na:na]

```

**Comment by produnis** [comment]
Am I the only one having Problem wih playlists?

**Comment by bedouin67** [comment]
No, same here, been going back to 11.1.4 because of this.

**Comment by kagemomiji** [comment]
@produnis @bedouin67 

I have fixed this issue. Could you try the following which you prefer.

[fixed airsonic.war](https://github.com/kagemomiji/airsonic-advanced/actions/runs/17224104558/artifacts/3848765153)
or
docker image: `ghcr.io/kagemomiji/airsonic-advanced:pr-774`

**Comment by bedouin67** [comment]
Can confirm that the problem is fixed. But now java 21 coredumps soon after startup, will have to stick with 11.1.4.
